### ISSUE TITLE
Add documentation to work with rfbrowser in distrobox

### ISSUE THREAD

**Issue by laguill** [MarketSquare/robotframework-browser#4612]
**Is your feature request related to a problem? Please describe.**
I working on Opensuse tumbleweed OS.
I installed distrobox with ubuntu as playwright is only supported on ubuntu.

Also my python environment is managed with uv.

I did not find a way to launch a the browser in headed mode from my robot script.

Here is my set up

## Install distrobox and podman

<details><summary>Details</summary>

```bash
sudo zypper in distrobox podman
```
</p>
</details> 

## Create a container

<details><summary>Details</summary>
<p>

```bash
distrobox create \
    --name ubuntu \
    --image ubuntu:24.04 \
    --home ~/distrobox/ubuntu \
	--additional-packages "micro nodejs npm"
```

</p>
</details> 

## Install python libraries and nodejs dependencies

<details><summary>Details</summary>
<p>

`pyproject.toml`

```python
[project]
name = "rfbrowser-distrobox"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "robotframework-browser[bb]>=19.12.0",
]

```

```bash
uv sync -U
npx playwright install-deps
uv run rfbrowser init chromium
```

</p>
</details> 

## Run minimal test

<details><summary>Details</summary>
<p>

`test.robot`

```robot
*** Settings ***
Library   Browser

*** Test Cases ***
Example Test
    New Page    https://playwright.dev
    Get Text    h1    contains    Playwright
```

```bash
uv run robot test.robot
```

</p>
</details> 

## Error
I am having an error

```bash
==============================================================================
Test
==============================================================================
[ ERROR ] Calling method '_end_test' of listener 'Browser' failed: Could not connect to the playwright process at 127.0.0.1:49151.
Example Test                                                          | FAIL |
Could not connect to the playwright process at 127.0.0.1:49151.
------------------------------------------------------------------------------
[ ERROR ] Calling method '_end_suite' of listener 'Browser' failed: Could not connect to the playwright process at 127.0.0.1:49151.
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
```

it is hard to tell if it is an error from my setup or something else.

Any body can help pe me on this ?

**Comment by laguill** [comment]
I wonder if it is an issue with mesa drivers or something dbus related ...

**Comment by aaltat** [comment]
Do not run `npx playwright install-deps`. Also because you are using Browser Batteries, instead of `uv run rfbrowser init chromium` run `uv run rfbrowser install chromium`

**Comment by aaltat** [comment]
I assume that issue is fixed and I will close the issue. If it is not, please ask again. Even better if you can ask in Robot Framework Slack and forum.

**Comment by laguill** [comment]
Hi @aaltat 
So I installed chromium as you suggested with `uv run rfbrowser install chromium`

And now I am getting an error when I run `uv run robot test.robot`

Error logs
<details><summary>Details</summary>
<p>

laguill@localhost:/home/laguill/Documents/00-Administratif/Personnel/****$ uv run robot test.robot
==============================================================================
Test
==============================================================================
Example Test                                                          | FAIL |
Error: browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /run/host/home/laguill/Documents/00-Administratif/Personnel/****/.venv/lib/python3.14/site-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/chromium_headless_shell-1200/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate,AutoDeElevate,RenderDocument,OptimizationHints --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagg...
    [ Message content over the limit has been removed. ]
...able-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --enable-automation --disable-infobars --disable-search-engine-choice-screen --disable-sync --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-ii8qI5 --remote-debugging-pipe --no-startup-window
  - <launched> pid=166661
  - [pid=166661][err] /run/host/home/laguill/Documents/00-Administratif/Personnel/****/.venv/lib/python3.14/site-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/chromium_headless_shell-1200/chrome-headless-shell-linux64/chrome-headless-shell: error while loading shared libraries: libnspr4.so: cannot open shared object file: No such file or directory
  - [pid=166661] <gracefully close start>
  - [pid=166661] <kill>
  - [pid=166661] <will force kill>
  - [pid=166661] exception while trying to kill process: Error: kill ESRCH
  - [pid=166661] <process did exit: exitCode=127, signal=null>
  - [pid=166661] starting temporary directories cleanup
  - [pid=166661] finished temporary directories cleanup
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================

</p>
</details>

**Comment by aaltat** [comment]
Looks like you are missing some dependencies 

error while loading shared libraries: libnspr4.so: cannot open shared object file: No such file or directory

**Comment by laguill** [comment]
I installed the missing dependecy with `sudo apt install libasound2t64`
And rerun the command `uv run rfbrowser init`

And now I have even more missing dependencies.

<details><summary>Details</summary>
<p>

╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgstreamer-1.0.so.0                            ║
║     libgtk-4.so.1                                    ║
║     libgraphene-1.0.so.0                             ║
║     libxslt.so.1                                     ║
║     libwoff2dec.so.1.0.2                             ║
║     libvpx.so.9                                      ║
║     libevent-2.1.so.7                                ║
║     libopus.so.0                                     ║
║     libgstallocators-1.0.so.0                        ║
║     libgstapp-1.0.so.0                               ║
║     libgstbase-1.0.so.0                              ║
║     liPlaywright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgstreamer-1.0.so.0                            ║
║     libgtk-4.so.1                                    ║
║     libgraphene-1.0.so.0                             ║
║     libxslt.so.1                                     ║
║     libwoff2dec.so.1.0.2                             ║
║     libvpx.so.9                                      ║
║     libevent-2.1.so.7                                ║
║     libopus.so.0                                     ║
║     libgstallocators-1.0.so.0                        ║
║     libgstapp-1.0.so.0                               ║
║     libgstbase-1.0.so.0                              ║
║     li
bgstpbutils-1.0.so.0                           ║
║     libgstaudio-1.0.so.0                             ║
║     libgsttag-1.0.so.0                               ║
║     libgstvideo-1.0.so.0                             ║
║     libgstgl-1.0.so.0                                ║
║     libgstcodecparsers-1.0.so.0                      ║
║     libgstfft-1.0.so.0                               ║
║     libflite.so.1                                    ║
║     libflite_usenglish.so.1                          ║
║     libflite_cmu_grapheme_lang.so.1                  ║
║     libflite_cmu_grapheme_lex.so.1                   ║
║     libflite_cmu_indic_lang.so.1                     ║
║     libflite_cmu_indic_lex.so.1                      ║
║     libflite_cmulex.so.1                             ║
║     libflite_cmu_time_awb.so.1                       ║
║     libflite_cmu_us_awb.so.1                         ║
║     libflite_cmu_us_kal16.so.1        bgstpbutils-1.0.so.0                           ║
║     libgstaudio-1.0.so.0                             ║
║     libgsttag-1.0.so.0                               ║
║     libgstvideo-1.0.so.0                             ║
║     libgstgl-1.0.so.0                                ║
║     libgstcodecparsers-1.0.so.0                      ║
║     libgstfft-1.0.so.0                               ║
║     libflite.so.1                                    ║
║     libflite_usenglish.so.1                          ║
║     libflite_cmu_grapheme_lang.so.1                  ║
║     libflite_cmu_grapheme_lex.so.1                   ║
║     libflite_cmu_indic_lang.so.1                     ║
║     libflite_cmu_indic_lex.so.1                      ║
║     libflite_cmulex.so.1                             ║
║     libflite_cmu_time_awb.so.1                       ║
║     libflite_cmu_us_awb.so.1                         ║
║     libflite_cmu_us_kal16.so.1
               ║
║     libflite_cmu_us_kal.so.1                         ║
║     libflite_cmu_us_rms.so.1                         ║
║     libflite_cmu_us_slt.so.1                         ║
║     libwebpdemux.so.2                                ║
║     libavif.so.16                                    ║
║     libharfbuzz-icu.so.0                             ║
║     libwebpmux.so.3                                  ║
║     libenchant-2.so.2                                ║
║     libsecret-1.so.0                                 ║
║     libhyphen.so.0                                   ║
║     libmanette-0.2.so.0                              ║
║     libx264.so

</p>
</details>

**Comment by laguill** [comment]
To solve dependencies issues I added playwright to my venv with `uv add playwright`
Then I install deps with `uv run playwright install-deps`

But I still having issues

<details><summary>Details</summary>
<p>

laguill@localhost:/home/laguill/Documents/00-Administratif/Personnel/Finance/Analyse_des_comptes/Sumeria$ uv run robot test.robot
==============================================================================
Test
==============================================================================
Example Test                                                          | FAIL |
TimeoutError: browserType.launch: Timeout 10000ms exceeded.
Call log:
  - <launching> /run/host/home/laguill/Documents/00-Administratif/Personnel/Finance/Analyse_des_comptes/Sumeria/.venv/lib/python3.14/site-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/chromium_headless_shell-1200/chrome-headless-shell-linux64/chrome-headless-shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate,AutoDeElevate,RenderDocument,OptimizationHints --enable-features=CDPScreenshotNewSurface --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --enable-automation --disable-infobars --disable-search-engine-choice-screen --disable-sync --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-1quniw --remote-debugging-pipe --no-startup-window
  - <launched> pid=245066

</p>
</details>

**Comment by aaltat** [comment]
It looks like you are missing some dependencies, but playwright does not log which one. Also there is not where good documentation on Playwright channel what actually should be installed. It would be better to ask from Slack or Forum, because I have done the installation only on the officially supported imaged.
