### ISSUE TITLE
Wait For Elements State disabled/enabled doesn't respect 10 sec wait time 

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#629]
**Describe the bug**
When using the function "Wait For Elements State"  <selector> enabled / disabled. It will fail frequently.

New message: Error: page.waitForFunction: Evaluation failed: TypeError: Cannot read property 'disabled' of null at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:17) at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:26) at eval (eval at callFunction (:304:29), <anonymous>:4:78) at onRaf (<anonymous>:2087:37) at <anonymous>:2097:13 at InjectedScript._runAbortableTask (<anonymous>:2154:24) at InjectedScript.pollRaf (<anonymous>:2078:21) at eval (eval at callFunction (:304:29), <anonymous>:4:39) at UtilityScript.callFunction (<anonymous>:305:24) at UtilityScript.<anonymous> (<anonymous>:1:44) Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs. 

It doesn't seem to respect the retry interval of 10seconds like with hidden or visible.

When I add "sleep 1s" before checking the state.... the check passes. But it would assume that robotframework-browser would do this when required (sleeping)

Found with v2.4.2

**Comment by emakaay** [comment]
Some extra information.

```
*** Test Cases ***
UC1000-TC001 Maak van een string een base64 gecodeerde string
    New Browser    chromium    headless=false
    New Context    
    New Page    https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_disabled2
    Wait For Elements State    id=myText      enabled

```   
 
When I execute this I get the following (unexpected error)  
```
Error: page.waitForFunction: Evaluation failed: TypeError: Cannot read property 'disabled' of null
    at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:17)
    at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:26)
    at eval (eval at callFunction (:304:29), <anonymous>:4:78)
    at onRaf (<anonymous>:2087:37)
    at <anonymous>:2097:13
    at InjectedScript._runAbortableTask (<anonymous>:2154:24)
    at InjectedScript.pollRaf (<anonymous>:2078:21)
    at eval (eval at callFunction (:304:29), <anonymous>:4:39)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

```
And here is the corresponding debug log
```

{"level":30,"time":"2021-01-06T16:32:08.887Z","pid":15020,"hostname":"<a host>","msg":"Listening on 53805"}
2021-01-06T16:32:09.115Z pw:api => browserType.launch started
2021-01-06T16:32:09.627Z pw:api <= browserType.launch succeeded
2021-01-06T16:32:09.652Z pw:api => browser.newContext started
2021-01-06T16:32:09.666Z pw:api <= browser.newContext succeeded
2021-01-06T16:32:09.666Z pw:api => browserContext.addInitScript started
2021-01-06T16:32:09.666Z pw:api <= browserContext.addInitScript succeeded
{"level":30,"time":"2021-01-06T16:32:09.667Z","pid":15020,"hostname":"<a host>","msg":"Changed active context"}
2021-01-06T16:32:09.696Z pw:api => browserContext.newPage started
2021-01-06T16:32:09.971Z pw:api <= browserContext.newPage succeeded
{"level":30,"time":"2021-01-06T16:32:09.971Z","pid":15020,"hostname":"<a host>","msg":"Video path: undefined"}
{"level":30,"time":"2021-01-06T16:32:09.971Z","pid":15020,"hostname":"<a host>","msg":"Changed active page"}
2021-01-06T16:32:09.971Z pw:api => page.goto started
2021-01-06T16:32:09.973Z pw:api navigating to "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_disabled2", waiting until "load"
2021-01-06T16:32:10.095Z pw:api   navigated to "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_disabled2"
2021-01-06T16:32:10.241Z pw:api   navigated to "about:blank"
2021-01-06T16:32:10.296Z pw:api   "domcontentloaded" event fired
2021-01-06T16:32:10.391Z pw:api   navigated to "about:blank"
2021-01-06T16:32:10.391Z pw:api   "domcontentloaded" event fired
2021-01-06T16:32:10.478Z pw:api   navigated to "https://accounts.google.com/o/oauth2/iframe#origin=https%3A%2F%2Fwww.w3schools.com&rpcToken=447218133.8222313&clearCache=1"
2021-01-06T16:32:10.545Z pw:api   "domcontentloaded" event fired
2021-01-06T16:32:10.547Z pw:api   "load" event fired
2021-01-06T16:32:10.547Z pw:api <= page.goto succeeded
{"level":30,"time":"2021-01-06T16:32:10.557Z","pid":15020,"hostname":"<a host>","msg":"unparsed args: e => !e.disabled, id=myText, {}"}
2021-01-06T16:32:10.558Z pw:api => page.$ started
2021-01-06T16:32:10.575Z pw:api <= page.$ succeeded
2021-01-06T16:32:10.576Z pw:api => page.waitForFunction started
2021-01-06T16:32:10.588Z pw:api <= page.waitForFunction failed
================= Original suppressed error =================
page.waitForFunction: Evaluation failed: TypeError: Cannot read property 'disabled' of null
    at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:17)
    at eval (eval at <anonymous> (eval at callFunction (:304:29)), <anonymous>:3:26)
    at eval (eval at callFunction (:304:29), <anonymous>:4:78)
    at onRaf (<anonymous>:2087:37)
    at <anonymous>:2097:13
    at InjectedScript._runAbortableTask (<anonymous>:2154:24)
    at InjectedScript.pollRaf (<anonymous>:2078:21)
    at eval (eval at callFunction (:304:29), <anonymous>:4:39)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\frame.js:344:48
    at Frame._wrapApiCall (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at Frame.waitForFunction (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\frame.js:341:21)
    at c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\page.js:454:60
    at Page._attributeToPage (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\page.js:202:20)
    at Page.waitForFunction (c:\python37\lib\site-packages\Browser\wrapper\node_modules\playwright\lib\client\page.js:454:21)
    at Object.<anonymous> (c:\python37\lib\site-packages\Browser\wrapper\index.js:70035:45)
    at step (c:\python37\lib\site-packages\Browser\wrapper\index.js:69941:23)
=============================================================
2021-01-06T16:32:10.598Z pw:api => page.screenshot started
2021-01-06T16:32:10.846Z pw:api <= page.screenshot succeeded
2021-01-06T16:32:10.856Z pw:api => page.title started
2021-01-06T16:32:10.858Z pw:api <= page.title succeeded
{"level":30,"time":"2021-01-06T16:32:10.862Z","pid":15020,"hostname":"<a host>","msg":"Changed active context"}
{"level":30,"time":"2021-01-06T16:32:10.862Z","pid":15020,"hostname":"<a host>","msg":"Changing current active page"}
{"level":30,"time":"2021-01-06T16:32:10.862Z","pid":15020,"hostname":"<a host>","msg":"Changed active page"}
2021-01-06T16:32:10.862Z pw:api => page.bringToFront started
2021-01-06T16:32:10.864Z pw:api <= page.bringToFront succeeded
2021-01-06T16:32:10.867Z pw:api => page.title started
2021-01-06T16:32:10.868Z pw:api <= page.title succeeded
{"level":30,"time":"2021-01-06T16:32:10.880Z","pid":15020,"hostname":"<a host>","msg":"Changed active context"}
{"level":30,"time":"2021-01-06T16:32:10.880Z","pid":15020,"hostname":"<a host>","msg":"Changing current active page"}
{"level":30,"time":"2021-01-06T16:32:10.880Z","pid":15020,"hostname":"<a host>","msg":"Changed active page"}
2021-01-06T16:32:10.880Z pw:api => page.bringToFront started
2021-01-06T16:32:10.881Z pw:api <= page.bringToFront succeeded
2021-01-06T16:32:10.883Z pw:api => browserContext.close started
2021-01-06T16:32:10.902Z pw:api <= browserContext.close succeeded
2021-01-06T16:32:10.933Z pw:api => browser.close started
2021-01-06T16:32:11.159Z pw:api <= browser.close succeeded    

```

**Comment by aaltat** [comment]
This is true, if there error in Pleywright side Browser library does not retry, instead the above error is shown. I think it is not correct and we should fix it.

**Comment by emakaay** [comment]
I looked at this problem.

I had the following xpath selector: //*[@id='ordernumber'] to select an input html element(Not there is only 1 element that matches this xpath (when using chrome browser)

When I did this: 
      `Browser.Wait For Elements State    //*[@id='ordernumber']     disabled`

I got an error message (as seen above) and the test fails
When I change the selector to '//index[@id='ordernumber']', the check is performed correctly.

I don't know if this a problem in robotframework-browser or playwright.
Does robotframework-browser accept all normal xpath queries ? Or are there any restrictions ?

**Comment by emakaay** [comment]
Please ignore previous solution.
I have tested this in Ride before placing 'solution' above.
I'm sure it worked, but know I see the problem again with //input ....  xpath selector

I don't understand this, but please ignore this solution

**Comment by emakaay** [comment]
I thought I was losing my marbles.... but now I see what causes the problem.

When using robotframework-browser HEADLESS checking if a field is disabled/enabled fails.
It doesn't matter if //*[@Id="someId"] or //input[@Id="someId"] is used.

When running robotframework-browser with a visible browser checking if the fields is 98 % accurate. Mostly it works, and 1 out of 10 it will still fail.

So I think the library or playwright is acting differently when in headless mode

**Comment by aaltat** [comment]
It's common or not unusual that browser or applications running in the browser might behave differently when running in headless mode. Example PDF preview doesn't work in headless mode and there have been several reports in SeleniumLibrary side from similar cases. 

But there is a bug in the Browser library that we don't respect the timeout if there is exception in playwright side.

**Comment by emakaay** [comment]
@aaltat ,
Anny chance that this problem in the browser library will be fixed soon?
Greets Erik

**Comment by aaltat** [comment]
Errr, no idea. Getting ready for the RoboCon 2021 is eating lots of extra time, everything has to be ready and recorded in this month. But after that there should be time.

**Comment by emakaay** [comment]
nice. RoboCon has some interesting topics !! 
Can anyone attend these meetings ? I assume it will be all online due to the pandemic

**Comment by aaltat** [comment]
Tickets are available at https://robocon.io/ Getting tickets will support Robot Framework development

**Comment by emakaay** [comment]
@aaltat 
Thanks. I had a few test failing because of this. A way to fix this is to use "Wait For Network Is Idle' before the check on field to be disabled/enabled. 

I was able to remove this when using browser 4.5.0. !!

**Comment by emakaay** [comment]
@aaltat 
I spoke too soon

I still have problems to check state disabled when page is refreshed, or a button triggers a change on the page.

Here are some debug logs:

Most of the time the test (which performs a "Wait For Elements State  <selector>  disabled, after a click on a button) fails. Mostly when using robotframework-browser headless. When using browser with visible browser the test sometimes works. Hope this helps in finding the problem. (tested with robotframework-browser 4.5.0)

[playwright-log-headless-error.txt](https://github.com/MarketSquare/robotframework-browser/files/6474243/playwright-log-headless-error.txt)
[playwright-log-visible-error.txt](https://github.com/MarketSquare/robotframework-browser/files/6474244/playwright-log-visible-error.txt)
[playwright-log-visible-noerror.txt](https://github.com/MarketSquare/robotframework-browser/files/6474245/playwright-log-visible-noerror.txt)

**Comment by aaltat** [comment]
4.5.0 doesn't have the fix, next release will have. If you want to try this fix, you need install from the repository directly.

**Comment by emakaay** [comment]
Sorry for that. Because the issue was closed I assumed the fix was in the
4.5.0 release.

Any idea when the release will be released which contains the fix?

Greets Erik

**Comment by aaltat** [comment]
Most likely we will push release out in next week.

**Comment by emakaay** [comment]
Euh.


Isn't it in release 4.5.2?

Greets

**Comment by aaltat** [comment]
Ah, true. I did forget that it was released.
