### ISSUE TITLE
Select Options By doesn't retry in 10sec interval

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#630]
**Describe the bug**
I have a webpage were fields are field one at a time.
Every time the focus is removed from a field (by pressing tab), a new field appears. These fields can be checked and filled with robotframework-browser, but dynamically filled drop downs fail.

I think because the dropdown is assembled by calling the back-end, to get the values shown. This takes a little while.
But the "Select Options by"  doesn't wait for the dropdown to be assembled. Therefore the required option can't be set, and the rest of the test fails....

I had assumed that robotframework-browser would try several times within an interval of 10 seconds.... But it doesn't.
When i add a "sleep 1s" statement and then set the required drop down option using "Select Options By" it works. 

But what I like about robotframework-browser doesn't need sleeps.... or code to make testing possible.

Is it supposed to work like this ? Or is some finetuning required in the library ?

Note: Fixed dropdown menus do not have this problem

**Comment by mkorpela** [comment]
Can you use `Wait until network idle` ?

**Comment by emakaay** [comment]
Hello mikko,

I will try.... I think it can help.... But I was under the impression that
robotframework-browser could solve this 'waiting game'.

That's one of the reasons why I like this framework a lot. I eliminates a
lot of technical code in our test, that distracts from the functional stuff
we are testing. Think like sleep/repeat/try until successful.

Are you suggesting a workaround or a temporary fix?  Shouldn't it be added
to the function 'select options by' ?

And if course: happy 2021

**Comment by emakaay** [comment]
Hello Mikko,

I started with the following (working) code
    sleep     1s        
    Browser.Select Options By    //*[@id="<a valid id>"]/select    value    <a valid value>

This worked. But I think sleep should be eliminated when possible. So I tried your suggestion.
    Browser.Wait Until Network Is Idle
    Browser.Select Options By    //*[@id="<a valid id>"]/select    value    <a valid value>

This didn't work. Here is the logging:
2021-01-05T08:48:20.439Z pw:api waiting for selector "//*[@id="<a valid id>"]/select"
2021-01-05T08:48:20.443Z pw:api   selector resolved to hidden <select tabindex="3" data-bind="options: planningscriterâ€¦>â€¦</select>
2021-01-05T08:48:20.446Z pw:api <= page.selectOption succeeded
{"level":30,"time":"2021-01-05T08:48:20.446Z","pid":3128,"hostname":"<a host>","msg":"Couldn't select any options"}
================= Original suppressed error =================
Error: No options matched [object Object]
    at Object.<anonymous> (c:\python37\lib\site-packages\Browser\wrapper\index.js:69333:31)
    at step (c:\python37\lib\site-packages\Browser\wrapper\index.js:69309:23)
    at Object.next (c:\python37\lib\site-packages\Browser\wrapper\index.js:69290:53)
    at fulfilled (c:\python37\lib\site-packages\Browser\wrapper\index.js:69281:58)

What I didn't expect was the selector to resolve to a hidden selector. That's why I changed the code as follows
    Browser.Wait For Elements State    <a valid id>     visible
    Browser.Select Options By    //*[@id="<a valid id>"]/select    value    <a valid value>

This caused no error, but also the required value was still not selected.  For know the sleep 1s is required to load the values from the backend and show the 'select' field in the browser. But I really would like to eliminate the usage of sleep were possible.

**Comment by mkorpela** [comment]
Add `Get Select Options` to support waiting for expected state of the options.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/637

**Comment by emakaay** [comment]
Hi Mikko !

Thanks for the update & fix

I tried it, but got another issue.

When using the following robot code (copied from log.html)
Browser . Get Selected Options //*[@id="<a valid id>"]/select, value, ==, <a valid drop down value>

I get the following error:
Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id="<a valid id>"]/select option' is not a valid XPath expression.
    at Object.queryAll (<anonymous>:3371:29)
    at InjectedScript._queryEngineAll (<anonymous>:1984:47)
    at InjectedScript.querySelectorAll (<anonymous>:1962:41)
    at eval (eval at callFunction (:304:29), <anonymous>:2:29)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

note the ' option' which is not in my xpath

**Comment by aaltat** [comment]
Would it be possible the error message without masking the xpath?

**Comment by emakaay** [comment]
helllo,

here is the unadjusted xpath:
Robot call
`Browser.Get Selected Options    //*[@id="planningscriteria.groepsafspraak"]/select    value    ==    Test    # this is dynamically filled dropdown. Make sure required value is in dropdown
`
log
```
Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id="planningscriteria.groepsafspraak"]/select option' is not a valid XPath expression.
    at Object.queryAll (<anonymous>:3371:29)
    at InjectedScript._queryEngineAll (<anonymous>:1984:47)
    at InjectedScript.querySelectorAll (<anonymous>:1962:41)
    at eval (eval at callFunction (:304:29), <anonymous>:2:29)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

**Comment by aaltat** [comment]
Interesting, by a quick look that seems like a valid xpath.

**Comment by emakaay** [comment]
I'm not quite sure what you mean.
The word 'option' is not after the xpath(//*[@id="planningscriteria.groepsafspraak"]/select). The word 'value' is. But it has 4 spaces before it

I added the code as seen in Ride(were 4 spaces are required to seperate different parameters)
![image](https://user-images.githubusercontent.com/72747481/103916886-42148d80-510d-11eb-8b77-f577386a2959.png)

I understand your reasoning, but I can't find the word option (it is not in the call to **Get Selected Options**. The first word after the xpath expression, but that is not shown in the error message. That, in fact, was the first thing I looked at ;)

**Comment by aaltat** [comment]
I see, in that case the error is confusing (it comes from Playwright side), out of the box I do not have better ideas.

**Comment by mkorpela** [comment]
@emakaay actually I did not suggest using `Get Selected Options`. I was proposing that core team implements a new keyword `Get Select Options` that returns all options.

**Comment by mkorpela** [comment]
I think that @emakaay found also a bug in `Get Selected Options` :D

**Comment by mnojek** [comment]
I have exactly the same error as @emakaay when using `Get Selected Options` with **valid** xpath selector for `select` element. I checked and the xpath works with other keywords but when used with `Get Selected Options` it throws:
`Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string '//div[@id='companySelector']/select option' is not a valid XPath expression.`
The problem I see is that the keyword **appends `option` word** at the end of the provided selector. 
At first I thought that I don't know how to use the keyword but now I think it is a bug.

**Comment by aaltat** [comment]
This should be now resolved with the 3.1.0 which contains playwright 1.8.0. Could someone be willing to test?

**Comment by emakaay** [comment]
I already tried, but could not install the node modules, using rfbrowser
init.

I already issued a new issue

**Comment by emakaay** [comment]
I did a re-test.

unfortunately this error message "Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[@id="<a valid id>"]/select option' is not a valid XPath expression." is still present in robotframework-browser v3.1.0

**Comment by emakaay** [comment]
Problem is also present in robotframework-browser 3.1.1 & 3.2.0.

**Comment by aaltat** [comment]
This is duplica of #757. I am closing this one, because 757 has less clutter and cleaner explanation where the fault is (In Browser library)
